title: Your Portfolio
description: Cybersecurity Portfolio using Jekyll
url: "https://yourusername.github.io"
baseurl: "/your-repo-name"  # Use this only if your repo is not the root repository.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
